export interface ChangelogEntry { version: string; date: string; changes: string[]; }
export const CHANGELOG: ChangelogEntry[] = [
  { version: '1.5.0', date: '2026-09-10', changes: [
    'League detail page: click any league in Competition to see Champions table + Top scorers table.',
    'Champions table format matches manual spreadsheet: team-colored rows, W / 2ND counts, years won / runners-up.',
    'Top scorer table: #, player, goals, nationality (color background), season, team (color background).',
    'Auto-normalize years: "38" → "2038", "27-28" → "2027-2028".',
    'Setting "Highlight seasons from year" (default 2026) — seasons from that year onwards render highlighted in Competition tables.',
    'Country header per league (ENGLAND / SPAIN / EUROPE …).',
    'Sample seed: Real Madrid (15 UCL) + PSG (2 UCL) so the League detail renders out of the box.',
    'Edit + delete buttons on every season card (label, national team, since month/year, current toggle).',
    'New season form: since-month datalist with jan/feb/…/dec, since-year auto-defaults from the last season.',
    'National-team badge (🌍 [team]) on season cards.',
    'Shortcuts from within a season: Career / Competition / Rivals pills at the top.',
    'Save sub-nav trimmed to just Compare + Manager.',
    'Contracts editable (✎ per contract).',
    'Awards moved under Career.',
    'Auto-fetch player photos in background when opening a season; API upgraded with 4 providers (FUTBIN, Wiki summary, Wiki search, DuckDuckGo) via weserv proxy.',
    'Bug fixes: owner_email set on save insert, national_since_month typed, useMemo unused import removed.',
  ] },
  { version: '1.4.0', date: '2026-09-10', changes: [
    'Games page: big app logo hero + gradient title.',
    'Games / Saves / Save pages: unified UX — search bar, Add opens inline form, drag & drop to reorder.',
    'Game types when adding a new game: EAFC (FIFA), Marvel Rivals (soon), Other. All existing data stays as EAFC.',
    'Save covers (URL or auto gradient with initials).',
    'Save page: iconos SVG muted en tiles, botón Contracts al lado de + New season, sub-nav pills (Dashboard / Compare / Contracts / Awards / Manager), buscador de temporadas.',
    'Season tabs: added Objectives, Gallery, Summary (carry-over).',
    'Objectives: pending / done / failed badges.',
    'Gallery: upload season screenshots to `season-photos` bucket with captions.',
    'Summary: final position, points, top scorer, key moment, next objective — carries over.',
    'Awards page: /save/:saveId/awards (name, category, recipient, year, notes).',
    'Manager route: /save/:saveId/manager.',
    'Settings: Changelog moved behind a button (opens its own modal).',
    'Header logo: cleaner (no emerald ring).',
  ] },
  { version: '1.3.0', date: '2026-09-09', changes: [
    'Rebrand: "Video juegos y más" with logo throughout.',
    'Logo cropped to 512x512 (centered on face) with emerald ring in header.',
    'Hero tiles: SVG icons + muted palette (blue/emerald/amber/rose), no emojis.',
    'Reorder mode: reorder hero tiles and seasons with up/down arrows.',
    'Compact season cards (3 per row) with team name to the left.',
    'New Season form: auto-fills next season label, only asks national team + since date.',
    'Contracts (new page): team autocomplete → auto-fills color and logo.',
    'Team catalog: 40+ pre-seeded top European clubs with color and crest.',
    'Rivals: autocomplete for team + logos via images.weserv.nl proxy.',
    'Player profile: EAFC-style card + "🔄 Buscar foto" button (FUTBIN + Wikipedia).',
    'Historical seasons seeded: Depor 25-30, Arsenal 33-36, Brighton, Napoli.',
    'Compare Seasons page (side-by-side squad diff).',
    'Global Search (top-right 🔍) across players, seasons, saves, rivals.',
    'Dashboard: real stats — trophies, runners-up, top 8 OVR, avg OVR.',
    'Language toggle EN / ES, dark / light theme toggle.',
    'Settings modal with Manager Profile link + changelog.',
    'Season tabs: Club Squad, International Squad, Injuries, Transfers, Ex-players.',
    'Salary + contract fields on players + salary history view.',
    'Defensive Add button: explicit error alerts and console logs.',
  ] },
];
export const APP_VERSION = CHANGELOG[0].version;
export const APP_NAME = 'Video juegos y más';
