create extension if not exists "uuid-ossp";
create table if not exists players (id uuid primary key default uuid_generate_v4(), name text not null, nationality text, birth_year int, photo_url text, external_id text, created_at timestamptz default now());
create table if not exists teams (id uuid primary key default uuid_generate_v4(), name text not null, country text, primary_color text, text_color text, crest_url text, created_at timestamptz default now());
create table if not exists competitions (id uuid primary key default uuid_generate_v4(), name text not null, country text, type text);
create table if not exists career_saves (id uuid primary key default uuid_generate_v4(), owner_email text not null, name text not null, notes text, is_active boolean default true, created_at timestamptz default now());
create table if not exists seasons (id uuid primary key default uuid_generate_v4(), save_id uuid references career_saves(id) on delete cascade, label text not null, team_id uuid references teams(id), team_name_snapshot text, team_color text, team_text_color text, formation text, start_date text, end_date text, is_current boolean default false, notes text, created_at timestamptz default now());
create index if not exists idx_seasons_save on seasons(save_id);
create type squad_role as enum ('starting','bench','reserve','loaned');
create table if not exists squad_players (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, player_id uuid references players(id), name_snapshot text not null, jersey int, position text, age int, ovr int, nationality_snapshot text, since_year int, role squad_role default 'starting', formation_slot int, canterano_status text, photo_url text, notes text, created_at timestamptz default now());
create index if not exists idx_squad_season on squad_players(season_id);
create table if not exists season_results (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, competition_id uuid references competitions(id), competition_name_snapshot text not null, result text, opponent text, score text, notes text, created_at timestamptz default now());
create table if not exists national_squad (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, country text not null, intl_label text, player_name text not null, club text, jersey int, position text, age int, ovr int, called_since int, club_since int, note text, role squad_role default 'starting', created_at timestamptz default now());
create table if not exists transfers (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, player_name text not null, direction text, from_team text, to_team text, amount text, transfer_type text, note text, created_at timestamptz default now());
create table if not exists injuries (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, player_name text not null, injury_type text, duration text, replaced_by text, note text, date text, created_at timestamptz default now());
create table if not exists ex_players (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, player_name text not null, position text, ovr int, current_team text, value text, seasons_played int, year_gone int, created_at timestamptz default now());
create table if not exists competition_champions (id uuid primary key default uuid_generate_v4(), save_id uuid references career_saves(id) on delete cascade, competition_name text not null, team_name text not null, team_country text, wins int default 0, runners_up int default 0, years_won text, years_runner_up text, created_at timestamptz default now());
create table if not exists photo_uploads (id uuid primary key default uuid_generate_v4(), owner_email text not null, storage_path text not null, extracted_json jsonb, linked_squad_player_id uuid references squad_players(id), created_at timestamptz default now());
insert into storage.buckets (id, name, public) values ('player-photos','player-photos',true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('screenshots','screenshots',false) on conflict (id) do nothing;
alter table career_saves enable row level security;
alter table seasons enable row level security;
alter table squad_players enable row level security;
alter table season_results enable row level security;
alter table national_squad enable row level security;
alter table transfers enable row level security;
alter table injuries enable row level security;
alter table ex_players enable row level security;
alter table competition_champions enable row level security;
alter table photo_uploads enable row level security;
alter table players enable row level security;
alter table teams enable row level security;
alter table competitions enable row level security;
create policy "open all" on career_saves for all using (true) with check (true);
create policy "open all" on seasons for all using (true) with check (true);
create policy "open all" on squad_players for all using (true) with check (true);
create policy "open all" on season_results for all using (true) with check (true);
create policy "open all" on national_squad for all using (true) with check (true);
create policy "open all" on transfers for all using (true) with check (true);
create policy "open all" on injuries for all using (true) with check (true);
create policy "open all" on ex_players for all using (true) with check (true);
create policy "open all" on competition_champions for all using (true) with check (true);
create policy "open all" on photo_uploads for all using (true) with check (true);
create policy "open all" on players for all using (true) with check (true);
create policy "open all" on teams for all using (true) with check (true);
create policy "open all" on competitions for all using (true) with check (true);
